#!/usr/bin/env python
""" read and process output files of sample_effective_current """

import numpy as np

import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import parse_sample_effective_current as ec



def make_mode_slice_plots(output_files, prefix=""):
    """
    plot slices of effective current for two modes,
    to be used for comparison in paper
    """
    out = ec.read_effective_current_output(output_files, prefix)

    # color plot of |j_eff| for TM010
    run = "TM010-m10"
    xs = out[run]["x"][:, 0, :]
    zs = out[run]["z"][:, 0, :]
    fig, ax = plt.subplots()
    j = out[run]["jtotal"][:, 0, :]
    abs_max = np.abs(j[np.isfinite(j)]).max()
    cplot = ax.pcolor(zs, xs, j/abs_max, cmap="Reds", vmin=0, vmax=1)
    ax.set_aspect("equal")
    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="5%", pad=0.05)
    fig.colorbar(cplot, cax=cax)
    ax.set_title("Effective current generated by TM010 source")
    fig.savefig("{}.png".format(run), dpi=160)
    plt.close(fig)

    # color plot of j_eff_phi for TE011
    run = "TE011-m10"
    xs = out[run]["x"][:, 0, :]
    zs = out[run]["z"][:, 0, :]
    fig, ax = plt.subplots()
    j = out[run]["re_jphi"][:, 0, :]
    abs_max = np.abs(j[np.isfinite(j)]).max()
    cplot = ax.pcolor(zs, xs, j/abs_max, cmap="Reds", vmin=0, vmax=1)
    ax.set_aspect("equal")
    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="5%", pad=0.05)
    fig.colorbar(cplot, cax=cax)
    ax.set_title("Effective current generated by TE011 source")
    fig.savefig("{}.png".format(run), dpi=160)
    plt.close(fig)


if __name__ == "__main__":

    paper_plot_runs = ["output-plot-TM010-m10.dat",
                       "output-plot-TE011-m10.dat"]
    make_mode_slice_plots(paper_plot_runs, prefix="output-plot-")



